---
title: "Main project"
---


::: callout-important
**Due date: 11:59pm on Sunday, 24 December 2023.**
:::

::: callout-note
Use the corresponding invite link in [this google doc](https://docs.google.com/document/d/1XTO7obXEr2Yxllxk48wnZ5e49ptPGMsMyl40KEZDGRg/edit?usp=sharing) (accessible with your EPFL account) to accept the project, and either join an existing team or create a new one. Once this is done, go to the [course GitHub organization](https://github.com/MATH-517) and locate the repo titled `main-project-TEAM-NAME` to get started.
:::



The goal of this project is quite broad, students are free to come up with their own ideas. While simulation studies are the designated topic, groups that found interesting data during the small project and would like to carry on analyzing it, or groups interested in studying a bit deeper one of the methodological concepts from this course are encouraged to approach the teachers during the exercises and discuss their ideas. **Prospective topics for the final project will be gradually revealed during the lectures.**

A part of the grade for the final project (10 % of the total grade, i.e. one quarter of the final project) will be awarded for value added (original data analysis, simulation study answering a previously unclear question, etc.). All of the prospective topics that will be introduced during the lecture will have this element, and by half-way through the semester (when the final project will start) it should be clear through the examples what the project should aspire to. We will also discuss this in person at some point, likely on Week 7. The remaining three quarters of the project (i.e. 30 % of the total grade) will be awarded for

* quality of the Markdown report
  - clarity, readability, structure, referencing, etc.
* graphical considerations
  - well chosen (as discussed during the course) graphics with captions, referenced from the main text
* concepts explored beyond the scope of the course
  - in the soft sense that they were not fully covered during classes
* overall quality
  - correctness, demonstration of understanding, etc.

A project seriously lacking in any of the criteria above will be penalized.

