project:
  type: website

website:
  page-navigation: true
  title: "MATH 517"
  description: "Homepage for MATH 517- Computational statistics and visualisation at EPFL, Fall 2023."
  site-url: https://github.com/MATH-517/MATH_517_website.github.io"

  repo-url: https://github.com/MATH-517/MATH_517_website
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#798b93"
    #logo: "images/logo.png"
    pinned: true
    align: center

    tools:
      - icon: github
        href: https://github.com/MATH-517/MATH_517_website
        text: "GitHub"

    style: docked
    search: true
    collapse-level: 1

    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
          - href: course-faq.qmd
      - section: "Exercises"
        contents:
          - href: exercises/exercise-01.qmd
            text: Exercise 1
      - section: "Assignments"
        contents:
          - href: assignments/assignment-01.qmd
            text: Assignment 1
      - section: "Projects"
        contents:
          - href: projects/project-01.qmd
          - href: projects/project-02.qmd
          - href: projects/project-tips-resources.qmd
            text: Tips + resources
      - section: "Ressources"
        contents:
          - section: "Coding introduction"
            contents:
              - href: ressources/computing/intro_to_r/index.qmd
                text: R
              - href: ressources/computing/intro_to_python/index.qmd
                text: Python
              - href: ressources/computing/intro_to_julia/index.qmd
                text: Julia
          - href: ressources/computing/computing-cheatsheets.qmd
            text: Cheatsheets
          - section: "Tutorials"
            contents:
              - href: ressources/tutorials/github.qmd
                text: GitHub
          - href: ressources/ressources.qmd
            text: All ressources
          

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Charles Dufour"
    background: "#5d6d74"


format:
  html:
    theme:
      light: [cosmo, style/sta101.scss]
    linkcolor: "#798b93"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
