---
title: "Assignment 1"
subtitle: "Introduction to Github and programming"
date: 09-22-2023
format: html
editor: visual
---

::: callout-important
**Due date: 11:59pm on Sunday, 1 October 2023.**
:::

::: callout-note
Use the corresponding invite link in [this google doc](https://docs.google.com/document/d/1XTO7obXEr2Yxllxk48wnZ5e49ptPGMsMyl40KEZDGRg/edit?usp=sharing) (accessible with your EPFL account) to accept the assignment. Then go to the [course GitHub organization](https://github.com/MATH-517) and locate the repo titled `ae-1-YOUR_GITHUB_USERNAME` to get started. 
:::


## Today

By the end of today you will...

- create a github account and familiarise yourself with git and GitHub
- accept the first assignment and submit your work
- make sure GitHub Classroom works as expected and you can submit your work.


## Assignment 

The goal of this assignment is for you to fit a linear model. For a refresher on linear models, see [the ressource for this week](../resources/week-01/recap-linear-regression.qmd). Your task will be to code a function that fits a linear model to a given dataset. You will need to fill in the blacks in the code located in your personal repository `ae-1-YOUR_GITHUB_USERNAME`.

Here is how to proceed: 

1. We expect you to know the basis of progamming in either R, Julia or Python. Please read the introduction to the language of your choice ([R](../resources/computing/intro_to_r/index.qmd), [Julia](../resources/computing/intro_to_julia/index.qmd), or [Python](../resources/computing/intro_to_python/index.qmd)) if it is not the case.


2. Read the `README.md` file in your assignment repository and follow the instructions there. (duplicated there for your convenience):

    You have to code a function that performs linear regression on a given dataset. The function should take as input a dataset (a matrix of size `n x d` where `n` is the number of observations and `d` is the number of features) and a vector of size `n` containing the labels. The function should return the vector of coefficients of the linear regression model.

    You are not allowed to use any library for linear regression. You can use libraries for basic operations (e.g. matrix multiplication, matrix inversion, etc.). You will have to check the correctness of your code by comparing the results with the ones obtained by traditional libraries (e.g. `sklearn` in Python, `lm` in R, `GLM.jl` in Julia).

    You will have to save a figure showing the data and add the line $X_{BMI}*\hat{\beta}_{BMI}$ as `result.png`, and modify the `README.md` file to add a table containing the coefficients of the linear regression model.