---
title: "Assignment 3"
subtitle: "Gloabl Optimal Bandwidth"
date: 10-13-2023
format: html
editor: visual
bibliography: ref.bib
---

::: callout-important
**Due date: 11:59pm on Sunday, 22 October 2023.**
:::

::: callout-note
Click on [this link](https://classroom.github.com/a/ct4FBOoh), then go to the [course GitHub organization](https://github.com/MATH-517) and locate the repo titled `ae-3-YOUR_GITHUB_USERNAME` to get started.
:::

## Recap on global optimal bandwidth

The Nadaraya--Watson kernel estimator of $m(x) = \mathbb{E}(Y|X=x)$

$$ \widehat{m}(x) = \frac{\sum_{i=1}^n K\left( \frac{X_i-x}{h} \right) Y_i}{ \sum_{i=1}^n K\left( \frac{X_i-x}{h} \right)} $$

is a weighted mean of the $Y_i$. 

Similarly to what we did with KDEs in week 3, we consider $$MSE\lbrace \widehat{m}(x) \rbrace = \mathrm{var}\lbrace \widehat{m}(x) \rbrace + \big[\mathrm{bias}\lbrace \widehat{m}(x) \rbrace\big]^2$$ and, dropping the little-o terms, we obtain $$AMSE\lbrace \widehat{m}(x) \rbrace = \frac{\sigma^2(x) \int \lbrace K(z) \rbrace ^2 dz}{f_X(x) n h_n} + \frac{1}{4} \lbrace m''(x)\rbrace ^2 h_n^4 \left(\int z^2 K(z) dz\right)^2.$$

Now, a local bandwidth choice can be obtained by optimizing AMSE. Taking derivatives and setting them to zero, we obtain $$h_{opt}(x) = n^{-1/5} \left[ \frac{\sigma^2(x) \int [K(z)]^2 dz}{m''(x) f_X(x) \int z^2 K(z) dz} \right]^{1/5}.$$


This is somewhat more complicated compared to the KDE case, because we have to estimate

-   the marginal density $f_X(x)$,
    -   let's say that we already know how to do this, e.g. by KDE even though that requires a choice of yet another bandwidth
-   the local variance function $\sigma^2(x)$, and
-   the second derivative of the regression functions $m''(x)$.

Again, like in the case of KDEs, the global bandwidth choice can be obtained by integration:

-   calculate $AMISE(\widehat{m}) = \int AMSE \lbrace \widehat{m}(x) \rbrace f_X(x) dx$, and
-   set $h_{AMISE} = \mathrm{arg\,min}_{h>0} AMISE(\widehat{m})$.


#### Rule of Thumb Plug-in Algorithm

Replace the unknown quantities in $$h_{AMISE} = n^{-1/5} \bigg[ \frac{\int K^2(z) dz \int \sigma^2(x) dx}{\int z^2 K(z) dz \int \lbrace m''(x) \rbrace^2 f_{X}(x) dx} \bigg]^{1/5}$$

by parametric OLS estimators

-   Assume homoscedasticity and a quartic kernel, then $$h_{AMISE} = n^{-1/5} \bigg( \frac{35 \sigma^2 \vert supp(X) \vert}{\theta_{22}} \bigg)^{1/5}, \quad \theta_{22}= \int \lbrace m''(x) \rbrace^2 f_{X}(x) dx$$
-   Block the sample in $N$ blocks and fit, in each block $j$, the model $$y_i = \beta_{0j} + \beta_{1j} x_i + \beta_{2j} x_i^2 + \beta_{3j} x_i^3 + \beta_{4j} x_i^4 + \epsilon_i$$ to obtain estimate $\hat{m}_j = \hat{\beta}_{0j} + \hat{\beta}_{1j} x_i + \hat{\beta}_{2j} x_i^2 + \hat{\beta}_{3j} x_i^3 + \hat{\beta}_{4j} x_i^4$


-   Estimate the unknown quantities by $$
    \begin{split}
     \hat{\theta}_{22}(N) &= \frac{1}{n} \sum_{i=1}^n \sum_{j=1}^N \hat{m}_j''(X_i) \hat{m}_j''(X_i)  \mathbb{1}_{X_i \in \mathcal{X}_j} \\
     \hat{\sigma}^2(N) &= \frac{1}{n-5N} \sum_{i=1}^n \sum_{j=1}^N \{Y_i - \hat{m}_j(X_i) \}^2 \mathbb{1}_{X_i \in \mathcal{X}_j}
    \end{split}
    $$

## Task

The goal is to study the (global, asymptotically optimal) bandwidth choice $h_{AMISE}$ on a simulated data example:

-   covariate $X$ from beta distribution Beta$(\alpha,\beta)$ 
-   response values $Y = m(X) + \epsilon$ where
    -   the regression function $m$ is given by $\sin\left(\left(\frac{x}{3+0.1}\right)^{-1}\right)$
    -   $\epsilon \sim \mathcal{N}(0,\sigma^2)$
-   fix $\sigma^2$ at some visually appealing value (e.g. $\sigma^2=1$ should be fine)
-   explore how $h_{AMISE}$ behaves depending on the following parameters (in case of a Shiny App, these will be sliders for the user to tweak):
    -   sample size `n`
    -   block size `N` (see  [@ruppert1995effective] for choosing the optimal block size)
    -   density of the covariate: beta parameters $\alpha$ and $\beta$
-   visualize (global, asymptotically optimal) bandwidth
    -   also find a way to visually incorporate the beta density

## Submission

Write a Markdown report explaining your findings. Use the `report.qmd` file to write your report [^1]. (Alternatively, any other format that produces an html and a pdf file is fine (e.g. Rmarkdown)).

The report should be self-contained and include all code necessary to reproduce your results (for help with virtual environments, see [this page](../resources/tips/virtual_environments.qmd)).


You can create a [Shiny App](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/) (or an interactive Jupyter notebook, Pluto notebook)  as it might be easier to play with the data. An interactive report (shiny app, notebook with interactive sliders, ...) is not required, but it is a good way to explore the data interactively. The `.qmd` report is required.


[^1]: `.qmd` files are [Quarto](https://quarto.org/) files, which can be used to write markdown report with R, Julia and Python (sometimes simultaneously).

